"""pykanban package initialization.

Exports the ``main`` function as a top‑level attribute so that the console
script generated by the packaging tools can call ``pykanban.main()`` directly.
"""

# TODO: create cli runner instead of re-exporting main
#
# Re_export the `main entry point from pykanban.main.
# The console script (e.g. .venv/bin/pykanban) does
# from pykanban import main and then sys.exit(main()).
# Without this re_export the import resolves to the pykanban.main *module*,
# which is not callable and results in the TypeError
from .main import main  # noqa: F401  (re_exported name)
