#!/usr/bin/env bash
# Integration test for extract_changelog.sh using the REAL CHANGELOG
# Run from the repo root, or from the scripts dir (the path is ../CHANGELOG.md)
set -euo pipefail

CHANGELOG_FILE="${1:-../CHANGELOG.md}"

echo "📄 Using changelog: $CHANGELOG_FILE"

# Check that the real file exists
if [[ ! -f "$CHANGELOG_FILE" ]]; then
  echo "❌ CHANGELOG.md not found at $CHANGELOG_FILE" >&2
  exit 1
fi

# Execute the extraction script exactly as release.sh would
echo "🔍 Running extract_changelog.sh..."
if ! raw_output=$(bash ./extract_changelog.sh "$CHANGELOG_FILE"); then
  echo "❌ extraction script failed" >&2
  exit 1
fi

# Parse version and notes from the output
actual_version=$(echo "$raw_output" | grep '^VERSION=' | cut -d'=' -f2- | tr -d '[:space:]')
actual_notes=$(echo "$raw_output" | awk '/^NOTES<<EOF/{flag=1;next}/^EOF/{flag=0}flag')

if [[ -z "$actual_version" ]]; then
  echo "❌ No VERSION found in extracted output" >&2
  exit 1
fi

# Write the report
REPORT_FILE="test_report.md"
cat >"$REPORT_FILE" <<REPORTEOF
# Changelog Extraction Test Report

**Source:** \`$CHANGELOG_FILE\`

## Extracted Version
\`\`\`
$actual_version
\`\`\`

## Extracted Notes
\`\`\`
$actual_notes
\`\`\`

*This file was generated by the integration test script.*
REPORTEOF

echo "✅ Report written to $REPORT_FILE"
echo "   Version: $actual_version"
echo "   Notes preview: $(echo "$actual_notes" | head -n 3)..."

exit 0
